name: fakenarr2022
channels:
  - pytorch
  - defaults
dependencies:
  - anyio
  - appnope
  - argon2-cffi
  - argon2-cffi-bindings
  - asttokens
  - attrs
  - babel
  - backcall
  - beautifulsoup4
  - blas
  - bleach
  - brotli
  - brotli-bin
  - brotlipy
  - bzip2
  - ca-certificates
  - certifi
  - cffi
  - charset-normalizer
  - cryptography
  - cycler
  - debugpy
  - decorator
  - defusedxml
  - entrypoints
  - executing
  - ffmpeg
  - fonttools
  - freetype
  - future
  - gettext
  - giflib
  - gmp
  - gnutls
  - icu
  - idna
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jedi
  - jinja2
  - jpeg
  - json5
  - jsonschema
  - jupyter_client
  - jupyter_core
  - jupyter_server
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - jupyterlab_widgets
  - kiwisolver
  - lame
  - lcms2
  - lerc
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcxx
  - libdeflate
  - libffi
  - libgfortran
  - libgfortran5
  - libiconv
  - libidn2
  - libopenblas
  - libopus
  - libpng
  - libsodium
  - libtasn1
  - libtiff
  - libunistring
  - libvpx
  - libwebp
  - libwebp-base
  - libxml2
  - llvm-openmp
  - lz4-c
  - markupsafe
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - mistune
  - munkres
  - nbclassic
  - nbclient
  - nbconvert
  - nbformat
  - ncurses
  - nest-asyncio
  - nettle
  - ninja-base
  - notebook
  - numpy-base
  - openh264
  - openssl
  - packaging
  - pandocfilters
  - parso
  - pexpect
  - pickleshare
  - pillow
  - pip
  - prometheus_client
  - prompt-toolkit
  - psutil
  - ptyprocess
  - pure_eval
  - pycparser
  - pygments
  - pyopenssl
  - pyparsing
  - pyrsistent
  - pysocks
  - python
  - python-dateutil
  - python-fastjsonschema
  - pytorch
  - pytz
  - pyzmq
  - readline
  - requests
  - send2trash
  - setuptools
  - six
  - sniffio
  - soupsieve
  - sqlite
  - stack_data
  - terminado
  - testpath
  - tk
  - tornado
  - traitlets
  - typing-extensions
  - typing_extensions
  - tzdata
  - urllib3
  - wcwidth
  - webencodings
  - websocket-client
  - wheel
  - widgetsnbextension
  - x264
  - xz
  - zeromq
  - zlib
  - zstd
  - cython
  - python-graphviz
  - pip:
    - absl-py
    - albumentations
    - appdirs
    - audioread
    - chex
    - coloredlogs
    - commonmark
    - diffusers
    - dm-tree
    - easydict
    - easyocr
    - etils
    - ffmpeg-python
    - filelock
    - flatbuffers
    - flax
    - ftfy
    - huggingface-hub
    - humanfriendly
    - imageio
    - importlib-metadata
    - importlib-resources
    - insightface>
    - ipywebrtc
    - jax
    - jaxlib
    - joblib
    - librosa
    - llvmlite
    - more-itertools
    - mpmath
    - msgpack
    - networkx
    - ninja
    - numba
    - numpy
    - onnx
    - onnxruntime
    - opencv-python-headless
    - opt-einsum
    - optax
    - pooch
    - prettytable
    - protobuf
    - pyclipper
    - python-bidi
    - pywavelets
    - pyyaml
    - qudida
    - regex
    - resampy
    - rich
    - scikit-image
    - scikit-learn
    - scipy
    - shapely
    - soundfile
    - sympy
    - threadpoolctl
    - tifffile
    - timm
    - tokenizers
    - toolz
    - torchvision
    - torchviz
    - tqdm
    - transformers
    - whisper
    - zipp
